### ISSUE TITLE
rockchip_wifi_get_oob_irq_bcmdhd_flag is undefined 

### ISSUE THREAD

**Issue by puffnfresh** [mrfixit2001/rockchip-kernel#12]
https://github.com/mrfixit2001/rockchip-kernel/blob/90df016b3a53212244fac674a8781faf0d48e245/drivers/net/wireless/rockchip_wlan/bcmdhd/dhd_gpio.c#L292

Using the RG552 config from batocera.

**Comment by mrfixit2001** [comment]
All fixed! Thanks for reporting!
