### ISSUE TITLE
a manual to compile the rockship-kernel

### ISSUE THREAD

**Issue by B0F1B0** [mrfixit2001/rockchip-kernel#2]
could you please give me an a manual / an example how to compile the rockship-kernel for RockPi4b?

-->There we have the salad<---

B0F1B0

**Comment by akhepcat** [comment]
Would love to see the prereqs and build-script.

Especially if you're doing it via cross-compile (and not on a rock-system)

**Comment by mrfixit2001** [comment]
Compiling a kernel is just like compiling any other GCC application, but understandably cross-compiling can be a bit mysterious. Hopefully this helps...

To cross-compile the Rockchip kernel you need an aarch64 toolchain. I use this one:
https://releases.linaro.org/components/toolchain/binaries/7.1-2017.08/aarch64-linux-gnu

And then when you run your make command you need to add the cross-compile prefix like this:
  CROSS_COMPILE=[PATH YOU INSTALLED THE TOOLCHAIN TO]/gcc-linaro-aarch64-linux-gnu/bin/aarch64-linux-gnu- make [FLAGS THAT IDENTIFY WHAT TO BUILD]

Obviously replace the stuff between the brackets with whatever is appropriate for your desired build. Here's a full make command from one of my builds, for reference:
CROSS_COMPILE="/home/host/lib/gcc-linaro-aarch64-linux-gnu/bin/aarch64-linux-gnu-" /usr/bin/make -j5 HOSTCC="/usr/bin/gcc -O2 -I/home/host/include -L/home/host/lib -Wl,-rpath,/home/host/lib" ARCH=arm64 INSTALL_MOD_PATH=/home/target DEPMOD=/home/host/sbin/depmod INSTALL_MOD_STRIP=1 Image
