### ISSUE TITLE
Please include kernel driver module for megaraid_sas

### ISSUE THREAD

**Issue by Naruni-Crawl** [mrfixit2001/rockchip-kernel#3]
LSI Logic's SAS based RAID controllers.  Many controllers use this driver.

[https://cateee.net/lkddb/web-lkddb/MEGARAID_SAS.html](url)

Thanks!

**Comment by mrfixit2001** [comment]
kernel driver added :)

**Comment by Naruni-Crawl** [comment]
Thanks buddy!
