### ISSUE TITLE
Virtualisation enabled kernel for Pinebook Pro

### ISSUE THREAD

**Issue by larsgn** [mrfixit2001/rockchip-kernel#4]
Hi,

I would like to experiment with KVM virtualisation on the pinebook pro, AFAIK the ARMv8 is KVM capable it just needs to be enabled in the kernel.

Can I enable virtualisation in the kernel config and compile a new one in a simple manner? I haven't done this on arm64 before.

**Comment by mrfixit2001** [comment]
virtualization enabled :)
